name: plant_app_01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/welcome_img.png
    - images/circle_img.png
    - images/loginpg_plant.png
    - images/Vector.png
    - images/circle_img2.png
    - images/circle_img3.png
    - images/pg4_logo.png
    - images/plant_01.png
    - images/sliding_dots.png
    - images/plant_02.png
    - images/pg4_logo2.png
    - images/plant_detail_img.png
    - images/plant_height_img.png
    - images/thermometer.png
    - images/Ciramic_pot.png
    - images/cart_button.png

