name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/home_pg_img/homePage_background.png
    - assets/images/gallary_pg_img/gallary_pg_bag.png
    - assets/images/gallary_pg_img/scrolling_dot1.png
    - assets/images/gallary_pg_img/scrolling_dot2.png
    - assets/images/gallary_pg_img/alone.png
    - assets/images/gallary_pg_img/dead_inside.png
    - assets/images/gallary_pg_img/heartless.png
    - assets/images/gallary_pg_img/song1_logo.png
    - assets/images/gallary_pg_img/dot.png
    - assets/images/gallary_pg_img/song2_logo.png
    - assets/images/player_pg_img/player_pg_bg.png
    - assets/images/player_pg_img/radix_icon.png
    - assets/images/player_pg_img/player_rectangle.png